services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: "no"
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./internal:/app/internal
      - ./:/app
  db:
    image: postgres:16.3-alpine
    restart: "no"
    ports:
      - 127.0.0.1:${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    # command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 3s
      retries: 3

volumes:
  database: