// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"$searchPokemon\" x-init=\"initData()\" class=\"p-10 bg-background w-full h-screen flex flex-col max-w-7xl m-auto\"><h1 class=\"text-3xl font-bold uppercase\">Pokedex - Golang </h1><h2 class=\"text-2xl font-bold\">Pokemon List </h2><div><input class=\"my-5 w-full px-5 py-4 bg-text text-black rounded border-gray-400 border-b-2\" placeholder=\"Search pokemon\" type=\"text\" max=\"50\" min=\"1\" x-model=\"searchInput\" @keyup=\"searchSubmit()\"></div><div class=\"flex-1 overflow-y-auto text-black no-scrollbar\"><template x-for=\"(pokemon, i) in pokemonList\" :key=\"pokemon.id\"><a class=\"flex gap-10 item-center px-5 py-10 border-gray-400 border-b-2 w-full rounded bg-slate-100 hover:bg-slate-300 transition mb-3\" :href=\"&#39;/&#39; + pokemon.pokedex + &#39;/&#39;\"><p x-text=\"pokemon.id + &#39;.&#39;\" class=\"text-2xl content-center\"></p><div class=\"flex flex-col item-start justify-start gap-2\"><h3 class=\"text-xl\" x-text=\"pokemon.name\">pokemon name </h3><div class=\"flex gap-2\"><div x-text=\"pokemon.type1\" class=\"p-2 text-white rounded\" :class=\"getPokemonType(pokemon.type1)\"></div><template x-if=\"pokemon.type2 !== &#39;&#39;\"><div x-text=\"pokemon.type2\" class=\"p-2 text-white rounded\" :class=\"getPokemonType(pokemon.type2)\"></div></template><template x-if=\"pokemon.legendary\"><div class=\"p-2 bg-yellow-300 rounded text-sm text-center\">Legendary</div></template></div></div></a></template></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
